{
 "title": "Простой дашборд",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "node_uname_info" }
   ]
  },
  {
   "title": "Network Traffic Received",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m])"
    }
   ]
  },
  {
   "title": "Singlestat Panel / Prometheus Time Series",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series_created_total"
    }
   ]
  },
  {
   "title": "Использование памяти",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  }
 ]
}