# my global config

global:
  scrape_interval: 10s
  evaluation_interval: 10s

## внешняя метка
  external_labels:
    region: eu-west-1
    env: prod
    team: frontend


rule_files:
  - rules.yml
alerting:
## Алертменеджер
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
  alert_relabel_configs:
  - source_labels: [severity]
    regex: info
    action: drop
scrape_configs:
  - job_name: prometheus
    static_configs:
     - targets:
       - localhost:9090
  - job_name: node
    static_configs:
     - targets:
       - nodeexporter:9100 
